project                  = "cwb06-prod"
project_prefix           = "cwb06"
region                   = "us-west1"
environment              = "prod"
user_management_base_url = "https://api.cwb06.dsgov.demo.nuvalence.io/um"
